### ISSUE TITLE
페이지 빌드 자동화 건의

### ISSUE THREAD

**Issue by sukso96100** [gnome-korea/gnome-kr-web#5]
새 그놈 코리아 홈페이지가 hugo 라는 정적 페이지 생성기 기반이고, gnome-kr-web 에 있는 원본을 빌드해서 나온걸 gnome-korea.github.io 에 넣는 방식으로 업데이트 하는것 같습니다. GitHub Actions 등 활용해서 빌드/배포 자동화 해 보는건 어떤가요?

**Comment by joone** [comment]
좋은 아이디어입니다. 혹시 경험이 있으시면 어떻게 하는지 알려주시면 좋겠습니다. 직접 해보시고 patch를 올려주셔도 됩니다.

**Comment by sukso96100** [comment]
조만간 패치 올려보겠습니다 :)

**Comment by joone** [comment]
잘 동작을 안하네요.

**Comment by joone** [comment]
https://github.com/gnome-korea/gnome-kr-web/runs/1048412376?check_suite_focus=true

Hugo에서 난 에러군요.

**Comment by joone** [comment]
themes/book이 clone이 안되서 생기는 문제 같습니다.

**Comment by sukso96100** [comment]
container 모드로 저장소 체크아웃을 하다보니, 서브모듈 클론이 안되어서 생기는 문제 같습니다.
hugo 패키지 설치해서 빌드하도록 수정해 보겠습니다

**Comment by joone** [comment]
ERROR 2020/08/31 04:02:20 Current theme does not support Hugo version 0.40.1. Minimum version required is 0.68

Hugo version이 낮네요.

**Comment by sukso96100** [comment]
저장소 설정의 Secrets 쪽에 DESTREPO 값을 gnome-korea/gnome-korea.github.io 로 설정해줘야 할것 같습니다.

**Comment by joone** [comment]
위와 같이 했는데, 에러가 나네요.
Determining the default branch
  /usr/bin/git ls-remote --quiet --exit-code --symref git@github.com:***.git HEAD
  git@github.com: Permission denied (publickey).
  ##[error]fatal: Could not read from remote repository.
  
  Please make sure you have the correct access rights
  and the repository exists.
  The process '/usr/bin/git' failed with exit code 128
  Waiting 20 seconds before trying again
  /usr/bin/git ls-remote --quiet --exit-code --symref git@github.com:***.git HEAD
  git@github.com: Permission denied (publickey).
  ##[error]fatal: Could not read from remote repository.
  
  Please make sure you have the correct access rights
  and the repository exists.
  The process '/usr/bin/git' failed with exit code 128
  Waiting 20 seconds before trying again
  /usr/bin/git ls-remote --quiet --exit-code --symref git@github.com:***.git HEAD
  git@github.com: Permission denied (publickey).
  ##[error]fatal: Could not read from remote repository.
  
  Please make sure you have the correct access rights
  and the repository exists.
  ##[error]The process '/usr/bin/git' failed with exit code 128

**Comment by sukso96100** [comment]
혹시 괜찮으시다면 제가 두 저장소 설정 한번 수정해봐도 될까요? SSH 키랑 Secret 정도면 수정하고 CI 다시 돌려보면 될것 같습니다.

**Comment by joone** [comment]
member로 초대했습니다. 해보시고, owner 권한이 필요하면 답글 남겨주세요.

**Comment by sukso96100** [comment]
감사합니다 :)

**Comment by sukso96100** [comment]
저장소 설정 접근은 아직 불가능 한것 같습니다. 두 저장소에 대한 admin 권한 추가 가능할까요?

**Comment by joone** [comment]
권한 드렸습니다.

**Comment by sukso96100** [comment]
이제 빌드 정상 작동 합니다.

**Comment by joone** [comment]
고맙습니다!

**Comment by joone** [comment]
@sukso96100  제가 페이지 빌드 자동화를 제 개인 블로그에 적용하려고 하는데, 동일하게 권한 문제 에러로  DESTREPO로 접근이 안되고 있는데, 지난번에 어떻게 해결하셨나요?

**Comment by sukso96100** [comment]
그놈 코리아 웹사이트의 경우 소스 저장소랑 실제 배포 저장소가 다른 저장소여서, 각 저장소에 SSH 키 페이를 등록하고 이를 활용해 배포 했습니다. 공개키를 웹사이트가 배포될 저장소에 Deploy Key 로 등록하고, 비공개키는 소스 저장소의 저장소 설정에서 Secret 으로 등록하여 사용 했습니다.

**Comment by sukso96100** [comment]
보통 GitHub Pages 로 정적 웹사이트 배포 할 때는 이렇게 저장소가 다르면 배포에 불편함이 있어서, 보통 같은 저장소에 다른 브랜치로 배포하는 경우가 많습니다. Ubucon Asia 2021 웹사이트도 Hugo + GitHub Pages 구성인데 아래 워크플로우 파일을 한번 참고해 보시면 좋을 것 같습니다.

https://github.com/ubucon-asia/2021/blob/main/.github/workflows/deploy.yml

**Comment by joone** [comment]
하나로 합칠 수 있으면 그게 더 좋을 것 같습니다. 답변 고맙습니다!
